name: buzzoffwebnew
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.6.4

  # UI / Utils
  intl: ^0.18.1
  lottie: ^2.2.0
  flutter_multi_formatter: ^2.5.0
  dropdown_search: ^5.0.6
  fl_chart: ^0.68.0
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8

  # Maps + HTTP
  google_maps_flutter: ^2.10.0
  google_maps_flutter_web: ^0.5.7
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/phi_area.json
    - images/logo.png
    - images/google.png
    - images/map.png
    - images/complains.png
    - images/analytics.png
    - images/fines_and_payments.png
    - images/community.png
    - images/image_placeholder.png
    - images/pfp.png
    - images/patient_form_icon.png
    - images/map_icon.png
    - images/patient_management_icon.png
    - images/analytics_icon.png
    - images/sl.ana.png
    - images/map.ana.png
    - images/map_map.png
    - images/tips1.png
    - images/tips2.png
    - images/tips3.png
    - images/tips4.png
    - images/tips5.png
    - images/tips6.png
    - images/tips7.png
    - images/tips8.png
    - images/tips9.png
    - images/tips10.png
    - images/tips11.png
    - images/tips12.png
    - images/tips13.png
    - images/bg.png
    - images/graph.png
    - images/fmaily.png
