// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqkqUO7bdiCo4HaLeeCPrGTwJecL9qb6A',
    appId: '1:497532763551:web:12c31e869b850cced851aa',
    messagingSenderId: '497532763551',
    projectId: 'buzzoff2',
    authDomain: 'buzzoff2.firebaseapp.com',
    storageBucket: 'buzzoff2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO0Qn0d-1ac-twGTNr-3ymtFqncZxawwQ',
    appId: '1:497532763551:android:2cac7a9f5cc70742d851aa',
    messagingSenderId: '497532763551',
    projectId: 'buzzoff2',
    storageBucket: 'buzzoff2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3kE4nl5hj37mAunnJF_LnzC-eUW8aTnI',
    appId: '1:497532763551:ios:c950b9081288862bd851aa',
    messagingSenderId: '497532763551',
    projectId: 'buzzoff2',
    storageBucket: 'buzzoff2.firebasestorage.app',
    iosClientId: '497532763551-jg4vebpj6isp10om7oon8tqv72odbdl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.buzzoffwebnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3kE4nl5hj37mAunnJF_LnzC-eUW8aTnI',
    appId: '1:497532763551:ios:c950b9081288862bd851aa',
    messagingSenderId: '497532763551',
    projectId: 'buzzoff2',
    storageBucket: 'buzzoff2.firebasestorage.app',
    iosClientId: '497532763551-jg4vebpj6isp10om7oon8tqv72odbdl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.buzzoffwebnew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqkqUO7bdiCo4HaLeeCPrGTwJecL9qb6A',
    appId: '1:497532763551:web:f060710707f3f70ad851aa',
    messagingSenderId: '497532763551',
    projectId: 'buzzoff2',
    authDomain: 'buzzoff2.firebaseapp.com',
    storageBucket: 'buzzoff2.firebasestorage.app',
  );
}
